const $=id=>document.getElementById(id),safe=v=>v===null||v===undefined||v===""?"—":v,key=(t,n)=>`${t}:${String(n||"").trim().toLowerCase()}`;
const state={pairs:[],schools:[],developments:[],addresses:[],coordinates:{},kb:[],results:[],compare:new Set(JSON.parse(localStorage.getItem("v7_compare")||"[]")),shortlist:new Set(JSON.parse(localStorage.getItem("v7_shortlist")||"[]")),notes:JSON.parse(localStorage.getItem("v7_notes")||"{}"),profile:"balanced",active:null,map:null,base:null,markers:null,focus:null,radius:null,compact:false};
const profiles={balanced:{school:.20,admission:.22,property:.20,family:.18,transit:.12,value:.08},admission:{school:.30,admission:.40,property:.10,family:.08,transit:.07,value:.05},investment:{school:.10,admission:.10,property:.42,family:.10,transit:.13,value:.15},family:{school:.20,admission:.15,property:.12,family:.30,transit:.18,value:.05}};
const load=async(url,fallback)=>{try{const r=await fetch(url);if(!r.ok)throw new Error();const t=await r.text();if(t.trim().startsWith("<"))throw new Error();return JSON.parse(t)}catch{return fallback}};
const coord=(t,n)=>state.coordinates[key(t,n)]||null;
const persist=()=>{localStorage.setItem("v7_compare",JSON.stringify([...state.compare]));localStorage.setItem("v7_shortlist",JSON.stringify([...state.shortlist]));localStorage.setItem("v7_notes",JSON.stringify(state.notes));$("compareCount").textContent=state.compare.size;$("shortlistCount").textContent=state.shortlist.size};
function val(p,k){return Number(p[k]||0)}
function decision(p){if(!p.overall_score_100)return null;const w=profiles[state.profile];return Math.round((val(p,"school_quality_30")/30*w.school+val(p,"admission_chance_20")/20*w.admission+val(p,"property_investment_20")/20*w.property+val(p,"family_living_15")/15*w.family+val(p,"transit_score_10")/10*w.transit+val(p,"value_5")/5*w.value)*1000)/10}
function kbFor(s,c){return state.kb.find(x=>x.school_name===s&&x.condo_name===c)}
function range(){let a=Number($("priceMin").value),b=Number($("priceMax").value);if(a>b)[a,b]=[b,a];$("priceText").textContent=`S$${(a/1e6).toFixed(2)}M – S$${(b/1e6).toFixed(2)}M`;return[a,b]}
function generatedForSchool(name){return state.kb.filter(k=>k.school_name===name).map(k=>{const d=state.developments.find(x=>x.name===k.condo_name)||{};return{id:`GEN:${k.school_id}:${k.condo_id}`,target_school:name,condo:k.condo_name,condo_id:k.condo_id,school_id:k.school_id,region:d.region||"",top_year:d.top_year,tenure:d.tenure,"3_bed_cost":d.three_bed_cost,price_min:d.price_min,price_max:d.price_max,kb:k,generated:true}})}
function apply(){state.profile=$("profile").value;const[a,b]=range(),q=$("search").value.trim(),school=$("schoolFilter").value,region=$("regionFilter").value,evidence=$("evidenceFilter").value,dist=$("distanceFilter").value,risk=$("riskFilter").value,top=Number($("topFilter").value||0),sort=$("sort").value;let base=state.pairs.map(p=>({...p,kb:kbFor(p.target_school,p.condo)}));const knownSchool=state.schools.find(s=>s.name.toLowerCase()===q.toLowerCase());if(q&&knownSchool&&!base.some(p=>p.target_school.toLowerCase()===q.toLowerCase()))base=generatedForSchool(knownSchool.name);state.results=base.filter(p=>{const k=p.kb,hay=`${p.target_school} ${p.condo}`.toLowerCase(),priceOk=p.generated||(!Number.isFinite(Number(p.price_min))||!Number.isFinite(Number(p.price_max))||(Number(p.price_max)>=a&&Number(p.price_min)<=b));return(!q||hay.includes(q.toLowerCase())||p.target_school===knownSchool?.name)&&priceOk&&(!school||p.target_school===school)&&(!region||p.region===region)&&(!risk||p.admission_risk===risk)&&(!top||Number(p.top_year||0)>=top)&&(!evidence||(k?.evidence||"missing")===evidence)&&(!dist||k?.category===dist)});state.results.sort((x,y)=>sort==="distance"?(x.kb?.best_m??Infinity)-(y.kb?.best_m??Infinity):sort==="admission"?val(y,"admission_chance_20")-val(x,"admission_chance_20"):sort==="property"?val(y,"property_investment_20")-val(x,"property_investment_20"):(decision(y)??-1)-(decision(x)??-1));$("searchMode").textContent=q&&knownSchool?(state.kb.some(k=>k.school_name===knownSchool.name)?`${knownSchool.name}: static distance records loaded.`:`${knownSchool.name} is known, but no static distance records are available yet.`):"Curated pairing search";renderStats();renderCards();renderMap()}
function renderStats(){$("pairCount").textContent=state.results.length;$("schoolCount").textContent=new Set(state.results.map(x=>x.target_school)).size;$("condoCount").textContent=new Set(state.results.map(x=>x.condo)).size;$("kbCount").textContent=state.kb.length;$("shown").textContent=`${state.results.length} shown`}
function badge(k){if(!k)return'<span class="badge missing">Distance missing</span>';return`<span class="badge ${k.category}">${k.label}${k.best_m?` · ${k.best_m} m`:""}</span>`}
function card(p){const id=p.id,k=p.kb,score=decision(p),saved=state.shortlist.has(id);return`<article class="card ${state.active===id?"active":""}" data-id="${id}"><div class="cardtop"><div><h3>${p.target_school}</h3><div class="condo">${p.condo}</div></div><b class="score">${score??"—"}</b></div><div class="pills">${badge(k)}${p.admission_risk?`<span>${p.admission_risk}</span>`:""}${p["3_bed_cost"]?`<span>${p["3_bed_cost"]}</span>`:""}${p.generated?'<span>Unscored nearby result</span>':""}</div><div class="cardactions"><button data-act="details">Details</button><button data-act="compare">Compare</button><button data-act="save">${saved?"Saved":"Save"}</button></div></article>`}
function renderCards(){$("cards").innerHTML=state.results.length?state.results.map(card).join(""):"<p>No matching results.</p>";document.querySelectorAll(".card").forEach(el=>el.onclick=e=>{const p=state.results.find(x=>x.id===el.dataset.id);if(!p)return;if(e.target.dataset.act==="details")openDetails(p);else if(e.target.dataset.act==="compare"){state.compare.add(p.id);persist()}else if(e.target.dataset.act==="save"){state.shortlist.has(p.id)?state.shortlist.delete(p.id):state.shortlist.add(p.id);persist();renderCards()}else focus(p)})}
function ensureMap(){if(state.map)return;state.map=L.map("map").setView([1.3521,103.8198],11);state.base=L.tileLayer("https://www.onemap.gov.sg/maps/tiles/Default/{z}/{x}/{y}.png",{detectRetina:true,minZoom:11,maxZoom:19}).addTo(state.map);state.markers=L.layerGroup().addTo(state.map);state.focus=L.layerGroup().addTo(state.map)}
function marker(type,label){return L.divIcon({className:"",html:`<div class="marker ${type}">${label}</div>`,iconSize:[28,28],iconAnchor:[14,14]})}
function renderMap(){ensureMap();state.markers.clearLayers();state.focus.clearLayers();if(state.radius){state.map.removeLayer(state.radius);state.radius=null}const bounds=[],seenS=new Set(),seenC=new Set();for(const p of state.results){const s=coord("school",p.target_school),c=coord("condo",p.condo);if(s&&!seenS.has(p.target_school)){seenS.add(p.target_school);L.marker([s.lat,s.lng],{icon:marker("school","S")}).addTo(state.markers).bindPopup(p.target_school);bounds.push([s.lat,s.lng])}if(c&&!seenC.has(p.condo)){seenC.add(p.condo);L.marker([c.lat,c.lng],{icon:marker("condo","C")}).addTo(state.markers).bindPopup(p.condo);bounds.push([c.lat,c.lng])}}if(bounds.length){state.map.fitBounds(bounds,{padding:[35,35],maxZoom:13});$("mapStatus").textContent=`${bounds.length} static coordinate points shown.`}else{$("mapStatus").textContent="No static coordinates loaded for the current results."}}
function focus(p){state.active=p.id;const s=coord("school",p.target_school),c=coord("condo",p.condo);state.focus.clearLayers();if(state.radius){state.map.removeLayer(state.radius);state.radius=null}const b=[];if(s){L.marker([s.lat,s.lng],{icon:marker("school","S")}).addTo(state.focus);state.radius=L.circle([s.lat,s.lng],{radius:1000,color:"#246b91",fillOpacity:.08}).addTo(state.map);b.push([s.lat,s.lng])}if(c){L.marker([c.lat,c.lng],{icon:marker("condo","C")}).addTo(state.focus);b.push([c.lat,c.lng])}if(b.length)state.map.fitBounds(b,{padding:[80,80],maxZoom:16});$("showAll").classList.remove("hidden");renderCards()}
function clearFocus(){state.active=null;$("showAll").classList.add("hidden");renderMap();renderCards()}
function openDetails(p){const k=p.kb;$("#details").innerHTML=`<h2>${p.target_school}</h2><h3>${p.condo}</h3><div class="detailgrid"><div><small>Decision score</small><b>${decision(p)??"Unscored"}</b></div><div><small>Distance category</small><b>${safe(k?.label)}</b></div><div><small>Best point</small><b>${safe(k?.best_label)} · ${safe(k?.best_m)} m</b></div><div><small>Worst point</small><b>${safe(k?.worst_label)} · ${safe(k?.worst_m)} m</b></div><div><small>Evidence</small><b>${safe(k?.evidence)}</b></div><div><small>Confidence</small><b>${safe(k?.confidence)}</b></div></div><p>${p.generated?"This is a nearby unscored result generated from the static distance database.":"This is a curated pairing with full decision data."}</p><label>My note<textarea id="note">${state.notes[p.id]||""}</textarea></label><button id="saveNote" class="btn gold">Save note</button>`;$("saveNote").onclick=()=>{state.notes[p.id]=$("note").value;persist()};$("drawer").classList.add("open")}
function compareCard(p){const k=p.kb||kbFor(p.target_school,p.condo);return`<article class="comparecard"><h3>${p.target_school}</h3><div class="condo">${p.condo}</div><div class="metric"><span>Decision</span><b>${decision(p)??"Unscored"}</b></div><div class="metric"><span>Distance</span><b>${safe(k?.label)} ${k?.best_m?`(${k.best_m} m)`:""}</b></div><div class="metric"><span>Evidence</span><b>${safe(k?.evidence)}</b></div><div class="metric"><span>Price</span><b>${safe(p["3_bed_cost"])}</b></div></article>`}
function findAny(id){return state.pairs.find(x=>x.id===id)||state.results.find(x=>x.id===id)}
function renderCompare(){$("compareGrid").innerHTML=[...state.compare].map(findAny).filter(Boolean).map(compareCard).join("")||"<p>No comparisons selected.</p>"}
function renderShortlist(){$("shortlistGrid").innerHTML=[...state.shortlist].map(findAny).filter(Boolean).map(compareCard).join("")||"<p>No saved options.</p>"}
function setView(n){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.view===n));$(n+"View").classList.add("active");if(n==="explore")setTimeout(()=>{state.map.invalidateSize();renderMap()},50);if(n==="compare")renderCompare();if(n==="shortlist")renderShortlist()}
function exportCsv(){const f=["target_school","condo","distance_category","best_distance_m","evidence","decision_score","3_bed_cost"],lines=[f.join(",")].concat(state.results.map(p=>{const k=p.kb||kbFor(p.target_school,p.condo),o={...p,distance_category:k?.label,best_distance_m:k?.best_m,evidence:k?.evidence,decision_score:decision(p)};return f.map(x=>`"${String(o[x]??"").replaceAll('"','""')}"`).join(",")}));const a=document.createElement("a"),b=new Blob([lines.join("\n")],{type:"text/csv"});a.href=URL.createObjectURL(b);a.download="p1-home-v7-results.csv";a.click()}
async function init(){[state.pairs,state.schools,state.developments,state.addresses,state.coordinates,state.kb]=await Promise.all([load("data/pairings-expanded.json?v=7.1.0",[]),load("data/schools-v6.json?v=7.1.0",[]),load("data/developments-v6.json?v=7.1.0",[]),load("data/residential-address-points.json?v=7.1.0",[]),load("data/coordinates.json?v=7.1.0",{}),load("data/distance-knowledge-base.json?v=7.1.0",[])]);const uniq=f=>[...new Set(state.pairs.map(x=>x[f]).filter(Boolean))].sort();for(const [id,vals] of [["schoolFilter",state.schools.map(x=>x.name).sort()],["regionFilter",uniq("region")],["riskFilter",uniq("admission_risk")]])for(const v of vals){const o=document.createElement("option");o.value=o.textContent=v;$(id).appendChild(o)}$("suggestions").innerHTML=[...state.schools.map(s=>s.name),...state.developments.map(d=>d.name)].sort().map(n=>`<option value="${n}"></option>`).join("");document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>setView(b.dataset.view));["search","profile","priceMin","priceMax","schoolFilter","regionFilter","evidenceFilter","distanceFilter","riskFilter","topFilter","sort"].forEach(id=>$(id).addEventListener("input",apply));$("reset").onclick=()=>{["search","schoolFilter","regionFilter","evidenceFilter","distanceFilter","riskFilter","topFilter"].forEach(id=>$(id).value="");$("priceMin").value=1e6;$("priceMax").value=3e6;clearFocus();apply()};$("fit").onclick=renderMap;$("showAll").onclick=clearFocus;$("reload").onclick=()=>{state.map.removeLayer(state.base);state.base=L.tileLayer("https://www.onemap.gov.sg/maps/tiles/Default/{z}/{x}/{y}.png",{detectRetina:true,minZoom:11,maxZoom:19}).addTo(state.map)};$("compact").onclick=()=>{state.compact=!state.compact;$("compact").textContent=state.compact?"Expanded":"Compact";renderCards()};$("closeDrawer").onclick=()=>$("drawer").classList.remove("open");$("clearCompare").onclick=()=>{state.compare.clear();persist();renderCompare()};$("clearShortlist").onclick=()=>{state.shortlist.clear();persist();renderShortlist()};$("exportBtn").onclick=exportCsv;persist();ensureMap();const coordinateCount=Object.keys(state.coordinates).length;$("dataStatus").className=`data-status ${coordinateCount&&state.kb.length?"ok":"warn"}`;$("dataStatus").textContent=coordinateCount&&state.kb.length?`${coordinateCount} static coordinates and ${state.kb.length} distance records loaded. No live geocoding is used.`:"Static data is incomplete. Run the Coordinate Builder, then copy its output files into public-app/data.";apply()}
init().catch(e=>document.body.innerHTML=`<main style="padding:30px"><h1>Unable to load Version 7</h1><p>${e.message}</p></main>`);